services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres_${POSTGRES_DB}
    restart: always
    # variables are set in the .env file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  cadip-station-mock:
    image: ghcr.io/rs-python/rs-testmeans_cadip-station-mock:latest
    container_name: cadip-station-mock
    restart: always
    ports:
      - 5000:5000

  rs-server:
    image: ghcr.io/rs-python/rs-server_services-cadip:latest
    container_name: rs-server
    restart: always
    command: python -m uvicorn rs_server.CADIP.cadip_backend:app --host 0.0.0.0 --port 8000
    # variables are set in the .env file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres # = the docker compose service name
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres
      - cadip-station-mock
    ports:
      - 8000:8000
