# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# dask-gateway-server image for local mode.
# We copy paste https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/Dockerfile
# and make modifications for the local mode.
#
# We cannot use the original ghcr.io/dask/dask-gateway-server image because it is made for k8s
# and uses a proxy file (that seems to be built with golang) that we don't have in local.

ARG PYTHON_VERSION=xxx
FROM python:${PYTHON_VERSION}-slim-bookworm

ARG DASK_GATEWAY_TAG=xxx

# Install tini and upgrade linux packages are updated to patch known
# vulnerabilities.
RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y \
        tini \
 && rm -rf /var/lib/apt/lists/*

# Create a non-root user to run as
RUN useradd --create-home --user-group --uid 1000 dask
USER dask:dask
ENV PATH=/home/dask/.local/bin:$PATH
WORKDIR /home/dask/

# Update pip version
RUN pip install --no-cache-dir --upgrade pip

# Install dask-gateway-server
COPY --chown=dask:dask . /opt/dask-gateway-server
RUN pip install --no-cache-dir \
        -r /opt/dask-gateway-server/Dockerfile.requirements.txt

# Same installation as in https://gateway.dask.org/install-local.html#installation
# Add bokeh and jupyter-server-proxy for the dask dashboard.
RUN pip install \
        dask-gateway==${DASK_GATEWAY_TAG} \
        dask-gateway-server[local]==${DASK_GATEWAY_TAG} \
        bokeh">=3.1.0" \
        jupyter-server-proxy

ENTRYPOINT ["tini", "-g", "--"]
CMD ["dask-gateway-server"]

# Set labels based on the Open Containers Initiative (OCI):
# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
#
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-demo"
LABEL org.opencontainers.image.ref.name="ghcr.io/rs-python/dask-gateway-server/base/local"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-demo/blob/develop/local-mode/docker/Dockerfile.dask-base-local"

LABEL org.opencontainers.image.version="dask-gateway==${DASK_GATEWAY_TAG} dask-gateway-server[local]==${DASK_GATEWAY_TAG}"
LABEL org.opencontainers.image.description="Same as 'ghcr.io/dask/dask-gateway-server' but for local mode."
