# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# We will add eopf to the dask-gateway-server image for local mode
# Declare ARG variables before the FROM instruction
ARG DASK_GATEWAY_TAG=xxx
FROM ghcr.io/rs-python/dask-gateway-server/base/local:${DASK_GATEWAY_TAG}

ARG PREFECT_TAG=xxx
ARG PREFECT_DASK_TAG=xxx

# Default user from parent image
ARG USER=dask:dask

# Install EOPF
COPY ./requirements.dask-eopf-local.txt /opt/
# NOTE, with older docker versions, use:
# RUN --mount=type=secret,id=GITLAB_EOPF_TOKEN \
# GITLAB_EOPF_TOKEN=$(cat /run/secrets/GITLAB_EOPF_TOKEN) pip install ...
RUN --mount=type=secret,id=GITLAB_EOPF_TOKEN,env=GITLAB_EOPF_TOKEN \
    pip install -U -r /opt/requirements.dask-eopf-local.txt

# Install complete dask subsets + prefect
RUN pip install \
    dask[complete] \
    prefect[aws]=="${PREFECT_TAG}" \
    prefect-dask=="${PREFECT_DASK_TAG}"

# Other installations
USER root
RUN apt update && apt install -y python3-pydot graphviz
USER $USER

# Install and auto configure opentelemetry
RUN pip install opentelemetry-distro opentelemetry-exporter-otlp opentelemetry-instrumentation-aws-lambda opentelemetry-test-utils && \
    opentelemetry-bootstrap -a install

# Clean everything
USER root
RUN rm -rf /tmp/whl /root/.cache/pip /var/cache/apt/archives /var/lib/apt/lists/* /opt/requirements.dask-eopf-local.txt
USER $USER

# Set labels based on the Open Containers Initiative (OCI):
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-demo"
LABEL org.opencontainers.image.ref.name="ghcr.io/rs-python/dask-gateway-server/eopf/local"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-demo/blob/develop/local-mode/docker/Dockerfile.dask-eopf-local"
