# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# We will add eopf to the dask-gateway-server image for local mode
# Declare ARG variables before the FROM instruction
ARG DASK_GATEWAY_TAG=xxx

# Get the contents from the rs-testmeans_dpr-processor-mock image
FROM ghcr.io/rs-python/rs-testmeans_dpr-processor-mock:latest AS dpr_mock

# Use the ARG value in the FROM statement
FROM ghcr.io/rs-python/dask-gateway-server/base/local:${DASK_GATEWAY_TAG}

ARG PREFECT_TAG=xxx
ARG PREFECT_DASK_TAG=xxx

# Default user from parent image
ARG USER=dask:dask
ARG USER_NAME=dask

USER root
COPY ./resources/layer-cleanup.sh ./resources/restore-apt.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh
USER $USER

############################################
# Install the DPR mockup (=fake processor) #
############################################

# Copy the src folder from the dpr_mock image
COPY --from=dpr_mock /src /src
WORKDIR /src/DPR

# Give USERNAME rights to write in /src
USER root
RUN chown -R $USER_NAME /src
USER $USER

# Export the poetry dependencies into a requirements.txt file then install it with pip
RUN \
    pip install -U pip && \
    pip install --no-cache-dir poetry pip-autoremove && \
    poetry self add poetry-plugin-export && \
    poetry export --without-hashes --format=requirements.txt > requirements.txt && \
    pip-autoremove -y poetry && \
    pip install -r requirements.txt && \
    rm -f requirements.txt && \
    layer-cleanup.sh

##################
# End DPR mockup #
##################

# Install complete dask subsets + prefect
RUN pip install \
        dask[complete] \
        prefect[aws]=="${PREFECT_TAG}" \
        prefect-dask=="${PREFECT_DASK_TAG}" \
    && layer-cleanup.sh

# Other installations
USER root
RUN \
    restore-apt.sh && apt update && \
    apt install -y python3-pydot graphviz && \
    layer-cleanup.sh
USER $USER

# Install and auto configure opentelemetry
RUN pip install opentelemetry-distro opentelemetry-exporter-otlp opentelemetry-instrumentation-aws-lambda opentelemetry-test-utils && \
    opentelemetry-bootstrap -a install && \
    layer-cleanup.sh

# Remove apt repository list and custom scripts
USER root
RUN rm -f /etc/apt/sources.list /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh
USER $USER

# Set labels based on the Open Containers Initiative (OCI):
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-demo"
LABEL org.opencontainers.image.ref.name="ghcr.io/rs-python/dask-gateway-server/eopf/mockup-local"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-demo/blob/develop/local-mode/docker/Dockerfile.dask-eopf-mockup-local"
