# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# We will add eopf to the dask-gateway-server image for local mode
# Declare ARG variables before the FROM instruction
ARG DASK_GATEWAY_TAG=xxx

# Get the contents from the rs-testmeans_dpr-processor-mock image
FROM ghcr.io/rs-python/rs-testmeans_dpr-processor-mock:latest as dpr_mock
# Get the wheel of the rs-dpr-service, in order to install it later on
FROM ghcr.io/rs-python/rs-dpr-service:latest as dpr_service

# Use the ARG value in the FROM statement
FROM ghcr.io/rs-python/dask-gateway-server/base/local:${DASK_GATEWAY_TAG}
ARG PREFECT_TAG=xxx
ARG PREFECT_DASK_TAG=xxx
ARG USER=dask:dask
ARG USER_NAME=dask

# Install complete dask subsets + prefect
RUN pip install \
    dask[complete]==2024.5.2 \
    distributed==2024.5.2 \
    prefect[aws]=="${PREFECT_TAG}" \
    prefect-dask=="${PREFECT_DASK_TAG}"

USER root
RUN apt update && apt install -y python3-pydot graphviz git gcc libpq-dev
USER $USER

# install rs-dpr-services dependencies
COPY ./requirements.dpr-service.txt /opt/
RUN pip install -U -r /opt/requirements.dpr-service.txt
# install rs-dpr-services wheel
COPY --from=dpr_service /rs-dpr-service/whl /tmp/whl
RUN pip install --no-cache-dir /tmp/whl/rs_dpr_service-*.whl

# Install and auto configure opentelemetry
RUN pip install opentelemetry-distro opentelemetry-exporter-otlp opentelemetry-instrumentation-aws-lambda opentelemetry-test-utils && \
    opentelemetry-bootstrap -a install

# Copy the src folder from the dpr_mock image
COPY --from=dpr_mock /src /src
WORKDIR /src/DPR
RUN python3.11 -m pip install --upgrade pip

# Install poetry
RUN python3.11 -m pip install --no-cache-dir poetry

SHELL ["/bin/bash", "-c"]
RUN poetry install --no-root
# tempfix
RUN pip install crcmod

USER root
RUN apt autoremove -y gcc git
# Give USERNAME rights to write in /src
RUN chown -R $USER_NAME /src

# Clean everything
RUN rm -rf /tmp/whl /root/.cache/pip /var/cache/apt/archives /var/lib/apt/lists/*
USER $USER

# Set labels based on the Open Containers Initiative (OCI):
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-demo"
LABEL org.opencontainers.image.ref.name="ghcr.io/rs-python/dask-gateway-server/eopf/mockup-local"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-demo/blob/develop/local-mode/docker/Dockerfile.dask-eopf-mockup-local"
