# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# We will add eopf to the dask-gateway-server image for local mode
# Declare ARG variables before the FROM instruction
ARG DASK_GATEWAY_TAG=xxx

# Get the contents from the rs-testmeans_dpr-processor-mock image
FROM ghcr.io/rs-python/rs-testmeans_dpr-processor-mock:latest as dpr_mock

# Use the ARG value in the FROM statement
FROM ghcr.io/rs-python/dask-gateway-server/base/local:${DASK_GATEWAY_TAG}

# Default user from parent image
ARG USER=dask:dask
ARG USER_NAME=dask

##########################
# Install the DPR mockup #
##########################

# Copy the src folder from the dpr_mock image
COPY --from=dpr_mock /src /src
WORKDIR /src/DPR

# Give USERNAME rights to write in /src
USER root
RUN chown -R $USER_NAME /src
USER $USER

# Install poetry
RUN pip install --upgrade pip && pip install --no-cache-dir poetry

# Export the poetry dependencies into a requirements.txt file then install it with pip
RUN \
    poetry self add poetry-plugin-export && \
    poetry export --without-hashes --format=requirements.txt > requirements.txt && \
    pip install -r requirements.txt && \
    rm -f requirements.txt

##################
# End DPR mockup #
##################

# Install complete dask subsets
RUN pip install dask[complete]

# Other installations
USER root
RUN apt update && apt install -y python3-pydot graphviz
USER $USER

# Install and auto configure opentelemetry
RUN pip install opentelemetry-distro opentelemetry-exporter-otlp opentelemetry-instrumentation-aws-lambda opentelemetry-test-utils && \
    opentelemetry-bootstrap -a install

# Clean everything
USER root
RUN rm -rf /tmp/whl /root/.cache/pip /var/cache/apt/archives /var/lib/apt/lists/*
USER $USER

# Set labels based on the Open Containers Initiative (OCI):
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-demo"
LABEL org.opencontainers.image.ref.name="ghcr.io/rs-python/dask-gateway-server/eopf/mockup-local"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-demo/blob/develop/local-mode/docker/Dockerfile.dask-eopf-mockup-local"
