# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# dask-gateway-server image for local mode.
# We copy paste https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/Dockerfile
# and make modifications for the local mode.

# Build the base dask-gateway image for local and cluster mode.

# Start from the customized https://github.com/dask/dask-gateway/blob/main/dask-gateway/Dockerfile
ARG BASE=xxx
FROM ${BASE}

ARG DASK_TAG=2024.5.2
ARG DASK_GATEWAY_TAG=2024.1.0

ARG user=dask
USER root
COPY ./layer-cleanup.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/layer-cleanup.sh
USER $user

# Add dask-gateway-server and other dependencies.
# Add bokeh and jupyter-server-proxy for the dask dashboard.
RUN pip install --upgrade pip && \
    pip install \
        dask==${DASK_TAG} \
        distributed==${DASK_TAG} \
        dask-gateway==${DASK_GATEWAY_TAG} \
        dask-gateway-server[local,kubernetes]==${DASK_GATEWAY_TAG} \
        bokeh">=3.1.0" \
        jupyter-server-proxy \
    && layer-cleanup.sh

# Remove custom scripts
USER root
RUN rm -f /usr/local/bin/layer-cleanup.sh
USER $user

# Set labels based on the Open Containers Initiative (OCI):
# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
#
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-demo"
LABEL org.opencontainers.image.ref.name="ghcr.io/rs-python/dask/dask-gateway"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-demo/blob/develop/local-mode/docker/Dockerfile.dask-base"
