#!/bin/sh
# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

# APP_MODULE holds the name of the service (eg. rs_server_adgs.fastapi.adgs_app:app)
# for which the env variables are set
# This value is passed by 'command' in docker-compose.yaml
APP_MODULE=${1}
python /home/user/.config/export_vars.py /home/user/.config/rs-server.yaml

# Read each line from the .env2, file generated by export_vars.py, and export the env variables in the running container
while IFS= read -r line; do
  export "$line"
done < .env2

# The entrypoint that is ran to start each service
exec python -m uvicorn "$APP_MODULE" \
  --host 0.0.0.0 --port 8000 --reload
