# Values from docker-compose:
# cadip-station = docker container name
# 5000 = port used by the application, as seen internally from the docker compose network.

cadip:
  auth:
    type: GenericAuth
    method: basic
    # credentials: # set using EODAG__cadip__auth__credentials__username and __password env vars
  products:
    GENERIC_PRODUCT_TYPE:
      productType: '{productType}'

  search:
    type: ODataV4Search
    api_endpoint: 'http://cadip-station:5000/Files'
    need_auth: true
    results_entry: responses | $
    metadata_mapping:
        id:
            - null
            - '$.Id'
        Name:
            - null
            - '$.Name'
        SessionID:
            - null
            - '$.SessionID'
        Channel:
            - null
            - '$.Channel'
        BlockNumber:
            - null
            - '$.BlockNumber'
        FinalBlock:
            - null
            - '$.FinalBlock'
        PublicationDate:
            - null
            - '$.PublicationDate'
        EvictionDate:
            - null
            - '$.EvictionDate'
        Size:
            - null
            - '$.Size'
        Retransfer:
            - null
            - '$.Retransfer'
        # Eodag Specific map
        startTimeFromAscendingNode:
            - null
            - '$.PublicationDate'
        completionTimeFromAscendingNode:
            - null
            - '$.PublicationDate'
        geometry: 'POLYGON((180 -90, 180 90, -180 90, -180 -90, 180 -90))'
        downloadLink: 'http://cadip-station:5000/Files({id})/$value'
        title: '$.Name'

    free_text_search_operations:
      $filter:
        union: ' OR '
        wrapper: '"{}"'
        operations:
            and:
              - 'PublicationDate gt {startTimeFromAscendingNode#to_iso_utc_datetime}'
              - 'PublicationDate lt {completionTimeFromAscendingNode#to_iso_utc_datetime}'

    pagination:
      max_items_per_page: 1000
      next_page_url_tpl: '{url}?{search}&$top={items_per_page}'
      total_items_nb_key_path: '$.total'

  download:
    type: HTTPDownload
    base_uri: 'http://cadip-station:5000/Files'
    metadata_mapping:
        uid: '$.Id'
        downloadLink: 'http://cadip-station:5000/Files({uid})/$value'
