auth_enabled: false

server:
  http_listen_port: 8000

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: tempo:4317

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks
