# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Run all demos

on:
  push:
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-env-external-data-sources:
    name: Build env for external data sources
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          # Checkout branch not pr (needed by git push)
          ref: ${{ case(github.event_name == 'pull_request', github.head_ref, '') }}
      - run: |
          set -x
          # This script creates .env-external-data-sources in local-mode/
          python local-mode/scripts/export_vars.py local-mode/config/rs-server.yaml

          # Commit the file if it changed
          to_commit="local-mode/.env-external-data-sources"
          if [[ -n $(git status -s $to_commit) ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add $to_commit
            git commit -m "Updated env for external data sources"
            git push
          fi

  test:
    runs-on: ubuntu-latest
    name: Run all demos
    needs: build-env-external-data-sources
    steps:
      - uses: actions/checkout@v6
        with:
          # Checkout branch not pr (so we get changes from build-env-external-data-sources)
          ref: ${{ case(github.event_name == 'pull_request', github.head_ref, '') }}
          submodules: true

      - name: Log into Docker registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run all demos in local mode
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          set -x

          # For main or develop, use the :latest image tags
          if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "develop" ]]; then
            export DOCKER_TAG=latest

          # Else, replace special characters by -
          else
            export DOCKER_TAG=$(sed "s/[^a-zA-Z0-9]/-/g" <<< "$BRANCH_NAME")
          fi

          # Run all demos
          ./test-rs-demo.sh
        shell: bash

      - name: Upload executed notebooks
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: notebook-outputs
          path: local-mode/notebook-outputs/
          if-no-files-found: ignore
