name: Run all demos

on:
  push:
  workflow_dispatch:

    # TODO ? versions as parameters
    # https://damienaicheh.github.io/github/actions/2022/01/20/set-dynamic-parameters-github-workflows-en.html

env:
  DOCKER_REGISTRY: ghcr.io

jobs:

  test:
    runs-on: ubuntu-latest
    name: Run all demos
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: true

      - name: Log into Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Init environment and run all demos
        run: |

          set -x
          
          # We need to be in the right directory to run docker compose build
          # to build the stac docker image
          cd ${GITHUB_WORKSPACE}/resources/stac/stac-fastapi-pgstac
          docker compose build # can take a few minutes

          # From the resources directory, pull the images
          cd ${GITHUB_WORKSPACE}/resources
          docker compose pull || true # ignore stac warnings about the docker images we built above

          # Run all services
          docker compose down; docker compose up -d
          docker compose ls
          sleep 5 # wait that all services are up before running the notebooks

          # Run all demos
          ${GITHUB_WORKSPACE}/scripts/run-notebooks.sh
          
          # Shutdown docker services and volumes
          docker compose down -v

        shell: bash