name: Run all demos

on:
  push:
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:

  test:
    runs-on: ubuntu-latest
    name: Run all demos
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: true

      - name: Log into Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Init environment and run all demos in local mode
        run: |
          set -x

          # We want to use docker images with tag=this_branch_name.
          branch_name=${{ github.ref_name }}

          # For main or develop, use the :latest image tags
          if [[ "$branch_name" == "main" || "$branch_name" == "develop" ]]; then
            docker_tag=latest

          # Else, replace special characters by -
          else
            docker_tag=$(sed "s/[^a-zA-Z0-9]/-/g" <<< "$branch_name")
          fi

          # Run the rs-demo local mode using these docker images, if they exist
          cd ${GITHUB_WORKSPACE}/local-mode
          ./test-docker-tag.sh "$docker_tag"

          # Run all services
          docker compose down; docker compose up -d
          docker compose ls

          # Run all demos
          ./run-notebooks.sh
          
          # Shutdown docker services and volumes
          docker compose down -v

        shell: bash