name: Run all demos

on:
  push:
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:

  test:
    runs-on: ubuntu-latest
    name: Run all demos
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Run pre-commit
        run: >
          echo
          ":information_source: This job checks that you have run \`pre-commit run --all-files\` in
          your local git repository before committing."
          >> $GITHUB_STEP_SUMMARY
      - uses: pre-commit/action@v3.0.1

      - name: Log into Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Init environment and run all demos in local mode
        run: |
          set -x

          # We want to use docker images with tag=this_branch_name.
          branch_name=${{ github.ref_name }}

          # For main or develop, use the :latest image tags
          if [[ "$branch_name" == "main" || "$branch_name" == "develop" ]]; then
            docker_tag=latest

          # Else, replace special characters by -
          else
            docker_tag=$(sed "s/[^a-zA-Z0-9]/-/g" <<< "$branch_name")
          fi

          # Run the rs-demo local mode using these docker images, if they exist
          cd ${GITHUB_WORKSPACE}/local-mode
          ./test-docker-tag.sh "$docker_tag"

          # Run all services
          # docker compose -f docker-compose-test-tag.yml up -d
          docker compose -f docker-compose-test-tag.yml up -d catalog-db postgres rs-server-catalog rs-server-cadip rs-server-adgs

          sleep 2
          curl http://localhost:8001/health || true
          curl http://localhost:8002/health || true
          curl http://localhost:8003/_mgmt/ping || true
          sleep 2
          curl http://localhost:8001/health || true
          curl http://localhost:8002/health || true
          curl http://localhost:8003/_mgmt/ping || true
          sleep 2
          curl http://localhost:8001/health || true
          curl http://localhost:8002/health || true
          curl http://localhost:8003/_mgmt/ping || true
          sleep 2
          curl http://localhost:8001/health || true
          curl http://localhost:8002/health || true
          curl http://localhost:8003/_mgmt/ping || true
          sleep 2
          curl http://localhost:8001/health || true
          curl http://localhost:8002/health || true
          curl http://localhost:8003/_mgmt/ping || true
          sleep 2
          curl http://localhost:8001/health || true
          curl http://localhost:8002/health || true
          curl http://localhost:8003/_mgmt/ping || true
          sleep 2
          curl http://localhost:8001/health || true
          curl http://localhost:8002/health || true
          curl http://localhost:8003/_mgmt/ping || true
          sleep 2
          curl http://localhost:8001/health || true
          curl http://localhost:8002/health || true
          curl http://localhost:8003/_mgmt/ping || true
          sleep 2
          curl http://localhost:8001/health || true
          curl http://localhost:8002/health || true
          curl http://localhost:8003/_mgmt/ping || true

          # Run all demos
          ./run-notebooks.sh "$docker_tag"

          # Shutdown docker services and volumes
          docker compose -f docker-compose-test-tag.yml down -v

        shell: bash
